language: android
android:
  components:
    # The SDK version used to compile your project
    - android-28
  licenses:
    - 'android-sdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - chmod +x gradlew
script:
  - ./gradlew testReleaseUnitTest