language: android
android:
  components:
    # The SDK version used to compile your project
    - android-28
  licenses:
    - 'android-sdk-license-.+'
before_install:
- chmod +x gradlew
script:
  - ./gradlew testReleaseUnitTest