language: android
android:
  components:
    # The SDK version used to compile your project
    - android-30
  licenses:
    - 'android-sdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.2"
  - chmod +x gradlew
script:
  - ./gradlew testReleaseUnitTest